Repository Tenet-Coding/Hacktoberfest-Projects, pull requests merged in 2021-10, with the labels that each got.

#44 int: Web app rock paper scissors
  Rock-Paper-Scissors/README.md
  Rock-Paper-Scissors/background.gif
  Rock-Paper-Scissors/index.html
  Rock-Paper-Scissors/index.js
  Rock-Paper-Scissors/style.css
Labels: enhancement, good first issue, Assigned, hacktoberfest, easy, hacktoberfest-accepted

#26 Background color changer project PR from branch
  Background_Color_Changer/Readme.md
  Background_Color_Changer/index.html
  Background_Color_Changer/main.js
  Background_Color_Changer/style.css
Labels: enhancement, Assigned, hacktoberfest, easy

#19 Word Counter
  Word_Counter/README.md
  Word_Counter/index.html
  Word_Counter/script.js
  Word_Counter/styles.css
Labels: enhancement, good first issue, hacktoberfest, Level = Medium

#38 Added my project swot analysis generator
  SWOT-Analysis-Generator/README.md
  SWOT-Analysis-Generator/compute.js
  SWOT-Analysis-Generator/generated.css
  SWOT-Analysis-Generator/generated.html
  SWOT-Analysis-Generator/generated.js
  SWOT-Analysis-Generator/index.html
  SWOT-Analysis-Generator/style.css
  SWOT-Analysis-Generator/swot.png
  SWOT-Analysis-Generator/swot1.png
Labels: enhancement, good first issue, hacktoberfest, Level = Medium, Participant issue, hacktoberfest-accepted

#41 Memory Game
  MemoryGame/README.md
  MemoryGame/blank.png
  MemoryGame/cheeseburger.png
  MemoryGame/fries.png
  MemoryGame/hotdog.png
  MemoryGame/ice-cream.png
  MemoryGame/index.html
  MemoryGame/index.js
  MemoryGame/milkshake.png
  MemoryGame/pizza.png
  MemoryGame/style.css
  MemoryGame/white.png
Labels: enhancement, good first issue, Assigned, easy, hacktoberfest-accepted

#55 Updating the PR_template
  .github/pull_request_template.md
Labels: documentation, hacktoberfest-accepted

#42 Commited Weather Forecast project
  Weather_Forecast/Readme.md
  Weather_Forecast/images/d.jpg
  Weather_Forecast/images/image.gif
  Weather_Forecast/index.html
  Weather_Forecast/script.js
  Weather_Forecast/styles.css
Labels: enhancement, good first issue, hacktoberfest, easy, hacktoberfest-accepted

#43 Notepad siddhantkhariwal
  Notepad-siddhantkhariwal/Readme.md
  Notepad-siddhantkhariwal/index.html
  Notepad-siddhantkhariwal/script.js
  Notepad-siddhantkhariwal/skrr.jpg
  Notepad-siddhantkhariwal/undraw_Add_notes_re_ln36.svg
  Notepad-siddhantkhariwal/undraw_Notebook_re_id0r.svg
Labels: enhancement, good first issue, Assigned, hacktoberfest, easy, hacktoberfest-accepted

#53 shades_colorGenerator by Ukesh-dev
  Shades-ColorGenerator/.gitignore
  Shades-ColorGenerator/README.md
  Shades-ColorGenerator/package-lock.json
  Shades-ColorGenerator/package.json
  Shades-ColorGenerator/public/favicon.ico
  Shades-ColorGenerator/public/index.html
  Shades-ColorGenerator/public/logo192.png
  Shades-ColorGenerator/public/logo512.png
  Shades-ColorGenerator/public/manifest.json
  Shades-ColorGenerator/public/robots.txt
  Shades-ColorGenerator/src/App.js
  Shades-ColorGenerator/src/SingleColor.js
  Shades-ColorGenerator/src/index.css
  Shades-ColorGenerator/src/index.js
  Shades-ColorGenerator/src/shades.PNG
  Shades-ColorGenerator/src/utils.js
Labels: enhancement, good first issue, hacktoberfest, easy, hacktoberfest-accepted

#58 Docs : Added hall of fame
  README.md
Labels: documentation, enhancement, good first issue, hacktoberfest, easy, hacktoberfest-accepted

#49 DarkMode from BajraYejoon
  Dark_Mode_Toggler/Readme.md
  Dark_Mode_Toggler/images/dark.gif
  Dark_Mode_Toggler/images/doc.svg
  Dark_Mode_Toggler/main.html
  Dark_Mode_Toggler/styler.css
  Dark_Mode_Toggler/toggler.js
Labels: enhancement, good first issue, hacktoberfest, easy, hacktoberfest-accepted

#62 Image cropper 26tanishabanik
  Image-Cropper/README.md
  Image-Cropper/cropper.py
  Image-Cropper/demo.gif
  Image-Cropper/ss.png
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#36 7suyash7 notes app
  NotesApp(7suyash7)/index.html
  NotesApp(7suyash7)/readme.md
  NotesApp(7suyash7)/script.js
Labels: enhancement, good first issue, Assigned, hacktoberfest, easy

#46 Ping pong game coderchirag
  ping-pong game/game.gif
  ping-pong game/index.html
  ping-pong game/index.js
  ping-pong game/readme.md
  ping-pong game/style.css
Labels: enhancement, good first issue, Assigned, hacktoberfest, easy

#79 Added Dice game
  Dice_Game/Readme.md
  Dice_Game/game.html
  Dice_Game/images/dice1.png
  Dice_Game/images/dice2.png
  Dice_Game/images/dice3.png
  Dice_Game/images/dice4.png
  Dice_Game/images/dice5.png
  Dice_Game/images/dice6.png
  Dice_Game/images/favicon.png
  Dice_Game/index.html
  Dice_Game/input.js
  Dice_Game/script.js
  Dice_Game/style.css
  Dice_Game/styles.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#68 Added roman-numeral-converter by h2o-Noob
  romanNumeralConverter_h2o-Noob/README.md
  romanNumeralConverter_h2o-Noob/index.html
  romanNumeralConverter_h2o-Noob/romCon.css
  romanNumeralConverter_h2o-Noob/script.js
  romanNumeralConverter_h2o-Noob/style.css
Labels: enhancement, good first issue, Assigned, hacktoberfest, easy
